### ISSUE TITLE
postcss-custom-properties breaks fallback vars, should be removed

### ISSUE THREAD

**Issue by lazd** [adobe/spectrum-css#1046]
## Description

Currently, this makes fallback variables break.

## Steps to reproduce

1.  Have the following in a component

```css
.spectrum-Test {
  --default: 50px;
  width: var(--large, var(--default));
  border: 1px solid blue;
}
.spectrum-Test--large {
  --large: 500px;
}
```
2. Build it with `gulp buildLite`
3. Observe `dist/index-vars.css` 
```css
.spectrum-Test {
  --default: 50px;
  width: var(--default);
  border: 1px solid blue;
}
.spectrum-Test--large {
  --large: 500px;
}
```

## Expected behavior

```css
.spectrum-Test {
  --default: 50px;
  width: var(--large, var(--default));
  border: 1px solid blue;
}

.spectrum-Test--large {
  --large: 500px;
}
```

## Additional context

Removing `postcss-custom-properties` from the `processors.js` fixes this
