### ISSUE TITLE
Rating: should not appear interactive on hover in readOnly mode

### ISSUE THREAD

**Issue by majornista** [adobe/spectrum-css#109]
### Expected Behavior
In some use cases, a Rating component needs to be readOnly, and simply show the current rating. When readOnly is true, the Rating should not respond to hover events.

### Actual Behavior
`.spectrum-Rating.is-readonly` style does not have `cursor: default; pointer-events: none`, so hovering over the control renders as if the component were still interactive.

### Reproduce Scenario (including but not limited to)
React Spectrum

See https://codepen.io/mijordan/pen/KEVEKO for fixed example.

#### Spectrum-CSS version
2.8.0

#### Sample Code that illustrates the problem
```css
.spectrum-Rating {
  &.is-disabled {
    cursor: default;
    pointer-events: none;
  }
}
```
Should be:
```css
.spectrum-Rating {
  &.is-disabled,
  &.is-readonly {
    cursor: default;
    pointer-events: none;
  }
}
```
