### ISSUE TITLE
Form (labels right) displayed on the left

### ISSUE THREAD

**Issue by matthewdeutsch** [adobe/spectrum-css#386]
## Steps to reproduce

1. https://opensource.adobe.com/spectrum-css/components/form/#Form-(labels-right)
2. Form labels are displayed on the left
 
## Expected behavior
Labels should display on the right

## Screenshots
![image](https://user-images.githubusercontent.com/700930/68159102-f9a88100-ff05-11e9-9526-e48db097cdf4.png)

## Environment
 - **Spectrum CSS version:** @spectrum-css/fieldlabel@2.0.0
 - **Browser(s) and OS(s):** all

**Comment by donroyco** [comment]
I think this is working as expected.
The label fields are indeed **on the left side** of the input field (as you mentioned), but they _are aligned_ to the right. 

```css
.spectrum-FieldLabel--right {
  display: inline-block;
  text-align: right; /* » Align text right */
  padding: 8px 8px 0 0;
}
```

See the `text-align: right;` that is specified in the CSS class.
