### ISSUE TITLE
ActionGroup wrapping is not working correctly

### ISSUE THREAD

**Issue by snowystinger** [adobe/spectrum-css#749]
## Description

When ActionGroup wraps, there is not margin between the lines and the second line gets an indent.

## Steps to reproduce

1. Go to http://opensource.adobe.com/spectrum-css/
2. Set chrome to mobile emulation and drag it as small as needed for ActionGroup to wrap
3. Observe the above stated issue

## Expected behavior

Wraps and no indentation and appropriate margin between lines

## Screenshots

![Screen Shot 2020-06-08 at 6 07 47 PM](https://user-images.githubusercontent.com/698229/84095194-82633000-a9b3-11ea-9a53-ea00c66b17a6.png)

## Environment
 - **Spectrum CSS version:** 
 - **Browser(s) and OS(s):**

**Comment by devongovett** [comment]
We worked around this in React Spectrum using a small shim for flex gap. See https://github.com/adobe-private/react-spectrum-v3/pull/600.

Interesting part is this:

```css
.flex-container {
  /* this is necessary so that the inner margins don't affect anything outside */
  display: flex;
}

.flex {
  display: flex;
}

.flex-gap {
  --gap: 0px;
  --column-gap: var(--gap);
  --row-gap: var(--gap);

  /* apply a negative margin to counteract the margin on each item at the edges */
  margin: calc(var(--row-gap) / -2) calc(var(--column-gap) / -2);

  /* increase the width and height to account for this margin */
  /* Add 1px to fix rounding error in Safari (╯°□°)╯︵ ┻━┻ */
  width: calc(100% + calc(var(--column-gap) + 1px));
  height: calc(100% + var(--row-gap));
}

.flex-gap > * {
  /* apply half of the gap to each side of every item */
  margin: calc(var(--row-gap) / 2) calc(var(--column-gap) / 2);
}
```

Then you just need to set the `--gap`, `--column-gap`, or `--row-gap` variables similar to how you'd set the native CSS properties. Would be cool to have this as a utility class in spectrum-css, and use this in various places.
